version: 0.2
env:
  parameter-store:
    SONAR_URL: "/petstore/dev/sonar/host"
    SONAR_ORG: "/petstore/dev/sonar/organization"
    SONAR_KEY: "/petstore/dev/sonar/projectKey"
    SONAR_TOKEN: "/petstore/dev/sonar/token"
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo login ERC
      - "$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)"
      - export SONAR_TOKEN=$SONAR_TOKEN
  build:
    commands:
      - echo Build started on ${date}
      - unset MAVEN_CONFIG
      - ./mvnw -ntp -B package -DskipTests
      - ./mvnw -ntp -B -D sonar.projectKey=$SONAR_KEY -D sonar.organization=$SONAR_ORG -Dsonar.host.url=$SONAR_URL -D spring.main.banner-mode=off verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - docker build -t $docker_img_name:$docker_tag .
      - docker tag $docker_img_name:$docker_tag $ecr_repo:latest
      - docker push $ecr_repo:latest
  post_build:
    commands:
      - echo Build completed on ${date}