version: 0.2
env:
  parameter-store:
    SONAR_TOKEN: "/petstore/dev/sonar/token"
    DOCKER_USERNAME: "/petstore/dev/docker/username"
    DOCKER_PASSWORD: "/petstore/dev/docker/password"
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - export ecs_name=awsomepletclinic-stack-awsomecluster44878E37-z4VccgaLdP1Q
      - export SONAR_TOKEN=$SONAR_TOKEN
      - export sq_prj="awsomepetclinic"
      - export sq_url="http://ec2-3-81-189-216.compute-1.amazonaws.com:9000"
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170.zip
      - unzip sonar-scanner-cli-4.4.0.2170.zip
      - export SCANNER="sonar-scanner-4.4.0.2170/lib/sonar-scanner-cli-4.4.0.2170.jar"         
      - echo login ERC
      - "$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)"
      - echo Login Docker
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - unset MAVEN_CONFIG
      - ./mvnw -ntp -B -Dcheckstyle.skip -Dspring.main.banner-mode=off -Dformat=JUNIT package org.owasp:dependency-check-maven:check
      - java -jar $SCANNER -D sonar.projectKey=$sq_prj -Dsonar.host.url=$sq_url -Dsonar.java.binaries=target/classes
      - docker build -t $docker_img_name:$docker_tag .
      - trivy -f json -o findings.json --exit-code 0 --severity CRITICAL,HIGH,MEDIUM --quiet $docker_img_name:$docker_tag
      - trivy -f template --template "@src/trivy/junit.tpl" -o findings.xml --exit-code 0 --severity CRITICAL,HIGH,MEDIUM --quiet $docker_img_name:$docker_tag
      - trivy --exit-code 1 --severity HIGH,CRITICAL --quiet $docker_img_name:$docker_tag      
      - docker tag $docker_img_name:$docker_tag $ecr_repo:latest
      - docker push $ecr_repo:latest
  post_build:
    commands:
      - printf '[{"name":"%s","imageUri":"%s"}]' $ecs_name $REPOSITORY_URI $ecr_repo:latest > imagedefinitions.json
      - echo Pushing Trivy findings to Security Hub
      - python3 sechub_parser.py
      - echo Build completed on `date`
reports:
  awsomepetclinic-coverage-report:
    files:
      - 'target/site/jacoco/jacoco.xml'
    file-format: 'JaCoCoXml'
  awsomepetclinic-dependencycheck-report:
    files:
      - 'target/dependency-check-junit.xml'
    file-format: 'JunitXml'
  awsomepetclinic-trivy-report:
    files:
      - 'findings.xml'
    file-format: 'JunitXml'
artifacts:
  files: imagedefinitions.json

