version: 0.2
env:
  parameter-store:
    SONAR_TOKEN: "/petstore/dev/sonar/token"
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170.zip
      - unzip sonar-scanner-cli-4.4.0.2170.zip
      - export SCANNER="sonar-scanner-4.4.0.2170/lib/sonar-scanner-cli-4.4.0.2170.jar"    
  pre_build:
    commands:
      - export SONAR_TOKEN=$SONAR_TOKEN
      - export sq_prj="awsomepetclinic"
      - export sq_url="http://ec2-3-81-189-216.compute-1.amazonaws.com:9000"
      - export pr_key="$PULL_REQUEST_ID"
      - export pr_branch=$(echo $SOURCE_REFERENCE | grep -o '[^/]*$')
      - export pr_base=$(echo $DESTINATION_REFERENCE | grep -o '[^/]*$')
      - git checkout $BRANCH
  build:
    commands:
      - echo Verifying Pull Request $PULL_REQUEST_ID started on `date`
      - unset MAVEN_CONFIG
      - ./mvnw -Dcheckstyle.skip -B -ntp -Dspring.main.banner-mode=off package
      - java -jar $SCANNER -Dsonar.projectKey=$sq_prj -Dsonar.host.url=$sq_url -Dsonar.pullrequest.key=$pr_key -Dsonar.pullrequest.branch=$pr_branch -Dsonar.pullrequest.base=$pr_base -Dsonar.qualitygate.wait=true -Dsonar.java.binaries=target/classes > sonar.log
  post_build:
    commands:
      - cat sonar.log
      - export quality_status=$(cat sonar.log | egrep -o "QUALITY GATE STATUS\W [A-Z]+" | grep -o '[^ ]*$')
      - export sq_link=$(cat sonar.log | grep -oP "View details on \S+")
      - |
        if [ $quality_status = "FAILED" ]; then
          content=$(echo "SonarQube Quality Gate Failed. $sq_link");
        else
          content=$(echo "SonarQube Quality Gate Passed. $sq_link");
          aws codecommit update-pull-request-approval-state --pull-request-id $PULL_REQUEST_ID --approval-state APPROVE --revision-id $REVISION_ID;
        fi
      - aws codecommit post-comment-for-pull-request --pull-request-id $PULL_REQUEST_ID --repository-name $REPOSITORY_NAME --before-commit-id $DESTINATION_COMMIT --after-commit-id $SOURCE_COMMIT --content "$content"    
reports:
  jacoco-report:
    files:
      - 'site/jacoco/jacoco.xml'
    file-format: 'JaCoCoXml'